print('test5: using C++ exceptions for the Lua panic function')
error "I'm exceptional!"
